### ISSUE TITLE
Can't install 0.3.0

### ISSUE THREAD

**Issue by kxra** [jetaggart/light-haskell#52]
Error: incorrect header check
        at Zlib._binding.onerror (zlib.js:295:17)

Fedora 21 x86_64

**Comment by galfaroi** [comment]
I have the same issue Ubuntu 12.04 as @kxra

**Comment by denislobanov** [comment]
Same error  as @kxra reproduced on Arch x86_64

**Comment by bkirwi** [comment]
Hmm, this one I might be able to reproduce. What's your LT version?

**Comment by denislobanov** [comment]
Light Table version
0.7.2
Binary version
0.8.6

**Comment by remk** [comment]
same issue with light table 0.7.2 on osx yosemite

**Comment by Goheeca** [comment]
Exactly the same error on Win 8.1 x64 with LT version 0.7.2.

**Comment by julianperrott** [comment]
I'm using Windows 10. When I try to install Haskell 0.3.0, in the console I see:
Error: incorrect header check
    at Zlib._binding.onerror (zlib.js:295:17)

I got it to work by not using light table's plug in manager...	

Close Light Table.
Download Zip of light-haskell from GitHub & copy folder light-haskell-master into \LightTable\plugins.

Make the folder writeable !
Open a command prompt and go to \LightTable\plugins\light-haskell-master & run "run-server.bat". Wait a while for cabal to configure, build and install stuff!

Start Light Table,
View Console,
View Connections,
Add a connection for 'Haskell',
Select folder  \LightTable\plugins\light-haskell-master\haskell folder
It should say "connected" in the console.

Next open a new file and save it with a .hs extension.

type in 1+2 and hit CTRL+ENTER, you should see Connecting, then connected, then GHCi should appear on the line. If you hit CTRL-ENTER again you will see '3'.

**Comment by tfausak** [comment]
:+1: I also get this error. I am using Light Table version 0.7.2 on OS X 10.10.3.

**Comment by xyc** [comment]
same issue with light table 0.7.2 on osx yosemite
